[custom]
; 不要随意改变关键字，否则会导致出错
; acl4SSR 规则

; 去广告：支持
; 自动测速：支持
; 微软分流：支持
; 苹果分流：支持
; 增强中国IP段：支持
; 增强国外GFW：支持

; 设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🎓 谷歌学术,https://raw.githubusercontent.com/willbon-dev/Config/main/Clash/Rule/GoogleScholar.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=💬 OpenAI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=💬 Claude,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list
ruleset=💬 Gemini,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Gemini.list
ruleset=🎮 EPIC,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 Origin,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 Sony,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 任天堂,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/willbon-dev/Config/main/Clash/Rule/ChinaDirect.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🇨🇳 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,[]GEOIP,LAN
ruleset=🇨🇳 国内直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
; 设置规则标志位

; 设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]♻️ 自动选择`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🇨🇳 国内直连`select`[]DIRECT`[]🚀 节点选择`.*

custom_proxy_group=💬 OpenAI`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=💬 Claude`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=💬 Gemini`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🎓 谷歌学术`select`[]DIRECT`[]🚀 节点选择`.*

custom_proxy_group=📹 YouTube`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🎥 Netflix`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=📺 哔哩哔哩`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🌍 国外媒体`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🚀 节点选择`.*

custom_proxy_group=Ⓜ️ Bing`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=Ⓜ️ OneDrive`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`.*

custom_proxy_group=🎮 Steam`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🎮 EPIC`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🎮 Sony`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🎮 Origin`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🎮 任天堂`select`[]DIRECT`[]🚀 节点选择`.*

custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
; 设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/willbon-dev/Config/main/Clash/Config/ClashConfig.yml
